# Generated by Django 3.2.6 on 2024-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('mvp', models.CharField(max_length=100)),
                ('mvs', models.CharField(max_length=100)),
                ('svp', models.CharField(max_length=100)),
                ('svs', models.CharField(max_length=100)),
                ('ro_1', models.BooleanField(default=False)),
                ('ro_2', models.BooleanField(default=False)),
            ],
        ),
    ]
