# Generated by Django 3.2.6 on 2024-02-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_auto_20230620_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('mvp', models.CharField(max_length=100)),
                ('mvs', models.CharField(max_length=100)),
                ('svp', models.CharField(max_length=100)),
                ('svs', models.CharField(max_length=100)),
                ('ro_1', models.BooleanField(default=False)),
                ('ro_2', models.BooleanField(default=False)),
            ],
        ),
          migrations.AlterField(
            model_name='feeds',
            name='MVP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='MVS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='RO_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='RO_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='SVP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='SVS',
            field=models.IntegerField(null=True),
        ),
    ]