# Generated by Django 3.2.6 on 2024-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_auto_20240224_1324'),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='feeds',
            name='MVP',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='MVS',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='RO_1',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='RO_2',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='SVP',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='SVS',
        ),

        # Re-add fields with the correct types
        migrations.AddField(
            model_name='feeds',
            name='MVP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='MVS',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='RO_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='RO_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='SVP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='SVS',
            field=models.IntegerField(null=True),
        ),
    ]